import Head from 'next/head';
import { useEffect, useState } from 'react';
import { v4 as uuid } from 'uuid';
import Cells from '../components/Cells';

export default function Home() {
  const [emojis, setEmojis] = useState([]);

  const asyncFetchEmojis = async () => {
    const response = await fetch('api/emojis');
    const data = await response.json();
    const array = data.map((res) => {
      return { ...res, id: uuid() };
    });
    setEmojis([...array]);
  };

  useEffect(() => {
    asyncFetchEmojis();
  }, []);

  const shuffleCells = () => {
    asyncFetchEmojis();
  };

  return (
    <div className=''>
      <Head>
        <title>Cells</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='w-full h-full bg-gray-700'>
        <div className='max-w-7xl w-full h-full mx-auto flex justify-center items-center flex-col'>
          <button
            className='border text-white py-2 px-4 max-w-7xl mb-10'
            onClick={shuffleCells}
          >
            Shuffle
          </button>
          <div className='max-w-xl w-full h-2/3 bg-gray-800 grid grid-cols-4 grid-rows-4 gap-1 p-1 '>
            <Cells emojis={emojis} setEmojis={setEmojis} />
          </div>
        </div>
      </main>
    </div>
  );
}
